

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowMultiQueries=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.lls.i18n.model

logging:
  level:
    com:
      lls:
        i18n:
          dao:
            mapper: debug


  jackson:
  time-zone: GMT+8